### ISSUE TITLE
File org-chrisle-netbeans-plugins-NbScratchFile.xml already exists in filesystem

### ISSUE THREAD

**Issue by kAlvaro** [Chris2011/NbScratchFile#15]
Now and then, when I start NetBeans I get a dialogue with this text:

> Warning
> ======
>
> File org-chrisle-netbeans-plugins-NbScratchFile.xml already exists in filesystem<br>
> C:\Users\ALVARO.GONZALEZ\AppData\Roaming\NetBeans\dev\config<br>
> (C:\Users\ALVARO.GONZALEZ\AppData\Roaming\NetBeans\dev\config\Modules\org-chrisle-netbeans-plugins-nbscratchfile.xml)

The dialogue closes automatically after a few seconds.

It doesn't happen every time. I have the impression that it tends to show up when NetBeans is trying to restore a previously opened project but I can't really confirm it.

It may also happen because I'm running [development versions](http://bits.netbeans.org/download/trunk/nightly/latest/) for NetBeans 8 (I need PHP/7 support). I run x64 version on Windows 10.

**Comment by Chris2011** [comment]
Thx for reporting this, I got the same thing sometimes, but I thought it was only in my dev enviroment. Strange and not good at all :/. It comes not often, sometimes and not in a periodic way...

**Comment by kAlvaro** [comment]
BTW, I got the same dialogue with 9.0 RC1. I haven't being able to use 9 thoroughly anyway since there's still basic stuff broken (such as Subversion support) and it corrupts your 8-dev profile. Whatever, there aren't new dev versions for 8.2 since late April—I guess all the efforts are put into "incubating".

**Comment by Chris2011** [comment]
OffTopic: Yes, atm we are close to the stable release of NetBeans 9.0. Atm we have RC1.

I will have a look into that strange problem, when I have time or when I refactor the UI to using Vue, instead of Knockout.

**Comment by Chris2011** [comment]
I didn't do any effort for this, but I created a new release with some refactoring etc. hope it is now working. Please check version 1.8.0 :)

**Comment by Chris2011** [comment]
Reopen, because of waiting for the answer.

**Comment by kAlvaro** [comment]
I've been using 1.8.0 on NetBeans IDE Dev (Build 201804200002) for a some hours during a couple of days (closing and opening the IDE now and then) and I haven't seen the dialogue so far.

**Comment by Chris2011** [comment]
Perfect, thx :)
