### ISSUE TITLE
[JDK 11 ISSUE]org.chrisle.netbeans.plugins.NbScratchFile - The module org.netbeans.api.htmlui would also need to be installed

### ISSUE THREAD

**Issue by albilu** [Chris2011/NbScratchFile#19]
Hello @Chris2011 ,
I am facing this issue with NBscratch using JDK 11+.

Here is the error message:
**Warning - could not install some modules:**
	**org.netbeans.libs.javafx - No module providing the capability org.openide.modules.jre.JavaFX could be found**.
	org.netbeans.api.htmlui - The module org.netbeans.libs.javafx would also need to be installed.
	**org.chrisle.netbeans.plugins.NbScratchFile - The module org.netbeans.api.htmlui would also need to be installed.**

I saw your comment about this issue in https://issues.apache.org/jira/browse/NETBEANS-3185

This is preventing to move to higher JDK.
So is there a work around for this? I really like your plugin, thanks for your work.

Thanks to help

**Comment by Chris2011** [comment]
Atm you need to use JDK 1.8.2 smth and maybe 9.0 will also work. There is no other workaround. I have problems to get the Plugin installing the needed dependencies for JavaFX for your operating system. It is smth missing in the manifest file.

**Comment by Chris2011** [comment]
I'm in contact with some people but I didn't get it working yet. Hopefully soon.

**Comment by albilu** [comment]
Got it thanks. Can you then please update the readme to mention its not supporting jdk9+ at the moment it will help people

**Comment by Chris2011** [comment]
Good point, thx for that :) Will do.

**Comment by Chris2011** [comment]
Done updating Readme. Last year :D. Didn't get any info from others to get it working. I'm out of my knowledge. Will see when I can fix this problem.

**Comment by Chris2011** [comment]
@albilu in general it is working for JDK > 9 I think, but you need to install somehow first the JavaFX implementaton for your Operating system. I want to do this with my plugin, but I can't find the solution how to do this, but you can do this by your own. Like createing a Dukescript Maven project will install the correct JavaFX Impl for your system and after this, you can install my plugin and it should work
