### ISSUE TITLE
Dialog shrinks when typing, outer box doesn't

### ISSUE THREAD

**Issue by kAlvaro** [Chris2011/NbScratchFile#3]
As you type to filter, the dialog shrinks but the outer box doesn't (see the animated GIF attached):

![nbscratchfile](https://user-images.githubusercontent.com/1327350/30611088-a274f74e-9d80-11e7-8b58-1222f45f08b0.gif)

**Comment by Chris2011** [comment]
Only to clarify it, The UI inside of the WebView, which is inside of the JDialog is shrinking, because of dynamic content heights. So the UL, where the result is inside, is shrinking, not the JDialog and maybe not the WebView too. Thx for reporting.

**Comment by felansu** [comment]
I test this bug in 1.7.1, don't occours

**Comment by Chris2011** [comment]
So in general the possibility i not implemented yet, that the dialog shrinks when the stuff inside the webview shrinks. I will have a look later how I can do that, I have no clue atm to handle it. I use a WebView inside the Dialog and the UL shrinks when there is less stuff to show as you can see in the screencast.

**Comment by Chris2011** [comment]
I moved from HTML4J back to swing, atm this will not happen anymore in version 2.0.0 which will be releases soon. The JList shrinks but the dialog stays as it is. Same behaviour as in IntelliJ.

**Comment by Chris2011** [comment]
Please check version 2.0.0 in the releases section.
