### ISSUE TITLE
Improper action id

### ISSUE THREAD

**Issue by junichi11** [Chris2011/NbScratchFile#5]
https://github.com/Chris2011/NbScratchFile/blob/8573227cecc21d6a95c44fcd49b6a4f61d148983/src/org/chrisle/netbeans/plugins/nbscratchfile/servicenode/ScratchRootNode.java#L10

I came across it. I guess that you just forgot to change it.

Thanks.

**Comment by junichi11** [comment]
BTW, It seems that whitespace is missing in README headers.

**Comment by Chris2011** [comment]
Thx for reporting.

> I came across it. I guess that you just forgot to change it.

Will fix it soon.

> BTW, It seems that whitespace is missing in README headers.

Will fix it soon too.

**Comment by Chris2011** [comment]
Fixed with release 1.6.0:  https://github.com/Chris2011/NbScratchFile/releases/tag/v1.6.0
